version: '3.8'
services:
  altshare:
    image: ghcr.io/3xjn/altshare:latest
    container_name: altshare
    restart: always
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
