version: '3.8'
services:
  altshare:
    image: ghcr.io/3xjn/altshare:latest
    container_name: altshare
    restart: always
    ports:
      - "5002:8080"
    env_file:
      - .env
    volumes:
      - /root/altshare/jwt_private_key.pem:/run/secrets/jwt_private_key.pem:ro
      - /root/altshare/jwt_public_key.pem:/run/secrets/jwt_public_key.pem:ro
    user: "0:0"